### ISSUE TITLE
readme-qt.rst links point to the wrong location

### ISSUE THREAD

**Issue by mascondante** [CryptoCoderz/INSN#6]
Document links in https://github.com/CryptoCoderz/INSN/blob/master/doc/readme-qt.rst refer to https://github.com/INSaNedev/INSaNe/blob/master/doc when they should refer to https://github.com/CryptoCoderz/INSN/blob/master/doc/

**Comment by CryptoCoderz** [comment]
Thank you, Updating this.

**Comment by CryptoCoderz** [comment]
Resolved with commit: https://github.com/CryptoCoderz/INSN/commit/ad66265912e6f561cf5d4a4388acbf34c80ff1d4
